spring:
  application:
    name: Academia

  datasource:
    url: jdbc:postgresql://10.10.10.52:5436/escuela
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      password: 1234

  jackson:
    property-naming-strategy: SNAKE_CASE

  graphql:
    graphiql:
      enabled: true

# --------------------------
# CORS CONFIGURATION
# --------------------------
graphiql:
  enabled: true
  mapping: /graphiql

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}